### ISSUE TITLE
Undefined symbol: gsl_sf_legendre_array_size (on Arch Linux)

### ISSUE THREAD

**Issue by elisaado** [SciRuby/rb-gsl#52]
I installed the gem, and tried it out but I got this error:
```LoadError: /home/eli/.gem/ruby/2.4.0/gems/gsl-2.1.0.3/lib/gsl_native.so: undefined symbol: gsl_sf_legendre_array_size - /home/eli/.gem/ruby/2.4.0/gems/gsl-2.1.0.3/lib/gsl_native.so
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/eli/.gem/ruby/2.4.0/gems/gsl-2.1.0.3/lib/gsl.rb:11:in `<top (required)>'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
```

OS: Arch Linux (x86_64)

**Comment by mikmakmuk** [comment]
I'm running into a similar issue on Arch Linux:

<code> Traceback (most recent call last): [SNIP]

1: from /home/mun/.gem/ruby/2.5.0/gems/gsl-2.1.0.3/lib/gsl.rb:11:in `<top (required)>'
/home/mun/.gem/ruby/2.5.0/gems/gsl-2.1.0.3/lib/gsl.rb:11:in `require': /home/mun/.gem/ruby/2.5.0/gems/gsl-2.1.0.3/lib/gsl_native.so: undefined symbol: gsl_sf_legendre_array_size - /home/mun/.gem/ruby/2.5.0/gems/gsl-2.1.0.3/lib/gsl_native.so (LoadError)
</code>

Did you ever find a solution?

**Comment by da2x** [comment]
The function is deprecated in GSL and the GSL gem need to update to reflect the deprecation.
https://www.rdocumentation.org/packages/gsl/versions/2.1-1/topics/gsl-deprecated
