### ISSUE TITLE
How to add GSL to PATH on Windows. 

### ISSUE THREAD

**Issue by ThePlasmaRailgun** [SciRuby/rb-gsl#53]
Hello, I have compiled GSL 2.4 on my Windows 10 PC and I want to then install rb-gsl using `gem install gsl`, but I was wondering what environment variables I should add my GSL library to. Thank you for the help!

**Comment by ThePlasmaRailgun** [comment]
If it helps, here is my error message:
```
gem install gsl
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing gsl:
        ERROR: Failed to build gem native extension.

    current directory: D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gsl-2.1.0.3/ext/gsl_native
D:/Programs/Ruby24-x64/bin/ruby.exe -r ./siteconf20171209-5276-1s62qho.rb extconf.rb
checking gsl version... 2.4
checking gsl cflags... -I/usr/include
checking gsl libs... -L/usr/lib -lgsl -lgslcblas -lm
checking for round()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=D:/Programs/Ruby24-x64/bin/$(RUBY_BASE_NAME)
        --with-gsl-version
        --with-gsl-cflags
        --with-gsl-libs
        --enable-atlas
        --disable-atlas
D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:768:in `try_func'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1055:in `block in have_func'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from D:/Programs/Ruby24-x64/lib/ruby/2.4.0/mkmf.rb:1054:in `have_func'
        from extconf.rb:131:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/gsl-2.1.0.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/gems/gsl-2.1.0.3 for inspection.
Results logged to D:/Programs/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/gsl-2.1.0.3/gem_make.out
```
